export type VocabularySeedItem = [string, string, string, string, string, string, string];

export const ADDITIONAL_B1_VOCABULARY: VocabularySeedItem[] = [
  // B1 cốt lõi
  ["corev-achieve", "B1", "achieve", "/əˈtʃiːv/", "đạt được", "She worked hard to achieve her goal.", "Cô ấy đã làm việc chăm chỉ để đạt mục tiêu."],
  ["corev-advantage", "B1", "advantage", "/ədˈvæntɪdʒ/", "lợi thế", "Online lessons have the advantage of flexibility.", "Các bài học trực tuyến có lợi thế về sự linh hoạt."],
  ["corev-avoid", "B1", "avoid", "/əˈvɔɪd/", "tránh", "Try to avoid using your phone while studying.", "Hãy cố tránh dùng điện thoại khi học."],
  ["corev-behave", "B1", "behave", "/bɪˈheɪv/", "cư xử", "The children behaved well during the trip.", "Bọn trẻ cư xử tốt trong chuyến đi."],
  ["corev-challenge", "B1", "challenge", "/ˈtʃælɪndʒ/", "thử thách", "Learning to speak confidently is a challenge.", "Học cách nói tự tin là một thử thách."],
  ["corev-choice", "B1", "choice", "/tʃɔɪs/", "sự lựa chọn", "You have a choice between two courses.", "Bạn có thể lựa chọn giữa hai khóa học."],
  ["corev-compare", "B1", "compare", "/kəmˈper/", "so sánh", "Compare the two pictures and find three differences.", "Hãy so sánh hai bức tranh và tìm ba điểm khác nhau."],
  ["corev-consider", "B1", "consider", "/kənˈsɪdər/", "cân nhắc", "We are considering moving to a quieter area.", "Chúng tôi đang cân nhắc chuyển đến khu vực yên tĩnh hơn."],
  ["corev-decision", "B1", "decision", "/dɪˈsɪʒən/", "quyết định", "It was a difficult decision to make.", "Đó là một quyết định khó đưa ra."],
  ["corev-describe", "B1", "describe", "/dɪˈskraɪb/", "mô tả", "Can you describe the person you met?", "Bạn có thể mô tả người bạn đã gặp không?"],
  ["corev-develop", "B1", "develop", "/dɪˈveləp/", "phát triển", "Reading helps you develop a wider vocabulary.", "Đọc sách giúp bạn phát triển vốn từ rộng hơn."],
  ["corev-difference", "B1", "difference", "/ˈdɪfrəns/", "sự khác biệt", "There is a big difference between knowing and using a word.", "Có sự khác biệt lớn giữa biết và sử dụng một từ."],
  ["corev-experience", "B1", "experience", "/ɪkˈspɪriəns/", "kinh nghiệm; trải nghiệm", "Working abroad was a valuable experience.", "Làm việc ở nước ngoài là một trải nghiệm quý giá."],
  ["corev-explain", "B1", "explain", "/ɪkˈspleɪn/", "giải thích", "Please explain the rule in your own words.", "Hãy giải thích quy tắc bằng lời của bạn."],
  ["corev-include", "B1", "include", "/ɪnˈkluːd/", "bao gồm", "The price includes breakfast and Wi-Fi.", "Giá đã bao gồm bữa sáng và Wi-Fi."],
  ["corev-increase", "B1", "increase", "/ɪnˈkriːs/", "tăng", "Daily practice can increase your confidence.", "Luyện tập hằng ngày có thể tăng sự tự tin của bạn."],
  ["corev-influence", "B1", "influence", "/ˈɪnfluəns/", "ảnh hưởng", "Friends can influence the choices we make.", "Bạn bè có thể ảnh hưởng đến những lựa chọn của chúng ta."],
  ["corev-manage", "B1", "manage", "/ˈmænɪdʒ/", "xoay xở; quản lý", "I managed to finish the task on time.", "Tôi đã xoay xở hoàn thành công việc đúng hạn."],
  ["corev-provide", "B1", "provide", "/prəˈvaɪd/", "cung cấp", "The website provides useful learning materials.", "Trang web cung cấp tài liệu học hữu ích."],
  ["corev-reason", "B1", "reason", "/ˈriːzən/", "lý do", "What is the main reason for your choice?", "Lý do chính cho lựa chọn của bạn là gì?"],
  ["corev-reduce", "B1", "reduce", "/rɪˈduːs/", "giảm", "Walking more can reduce stress.", "Đi bộ nhiều hơn có thể giảm căng thẳng."],
  ["corev-suggest", "B1", "suggest", "/səˈdʒest/", "đề nghị; gợi ý", "I suggest taking a short break.", "Tôi đề nghị nghỉ một lát."],
  ["corev-support", "B1", "support", "/səˈpɔːrt/", "hỗ trợ", "My family supports my decision to study abroad.", "Gia đình ủng hộ quyết định du học của tôi."],
  ["corev-succeed", "B1", "succeed", "/səkˈsiːd/", "thành công", "You will succeed if you keep practising.", "Bạn sẽ thành công nếu tiếp tục luyện tập."],

  // Đời sống hằng ngày
  ["dailyv-appointment", "B1", "appointment", "/əˈpɔɪntmənt/", "cuộc hẹn", "I have a dentist appointment tomorrow morning.", "Tôi có lịch hẹn nha sĩ vào sáng mai."],
  ["dailyv-borrow", "B1", "borrow", "/ˈbɑːroʊ/", "mượn", "Could I borrow your charger for an hour?", "Tôi có thể mượn bộ sạc của bạn một giờ không?"],
  ["dailyv-cancel", "B1", "cancel", "/ˈkænsəl/", "hủy", "We had to cancel dinner because of the storm.", "Chúng tôi phải hủy bữa tối vì cơn bão."],
  ["dailyv-clean-up", "B1", "clean up", "/kliːn ʌp/", "dọn dẹp", "Let's clean up the kitchen after dinner.", "Hãy dọn bếp sau bữa tối."],
  ["dailyv-comfortable", "B1", "comfortable", "/ˈkʌmftəbəl/", "thoải mái", "These shoes are comfortable enough for walking.", "Đôi giày này đủ thoải mái để đi bộ."],
  ["dailyv-crowded", "B1", "crowded", "/ˈkraʊdɪd/", "đông đúc", "The supermarket is usually crowded on Sunday.", "Siêu thị thường đông đúc vào Chủ nhật."],
  ["dailyv-decide", "B1", "decide", "/dɪˈsaɪd/", "quyết định", "We need to decide what to cook tonight.", "Chúng ta cần quyết định nấu gì tối nay."],
  ["dailyv-deliver", "B1", "deliver", "/dɪˈlɪvər/", "giao hàng", "They will deliver the table this afternoon.", "Họ sẽ giao chiếc bàn vào chiều nay."],
  ["dailyv-entrance", "B1", "entrance", "/ˈentrəns/", "lối vào", "Meet me near the main entrance.", "Hãy gặp tôi gần lối vào chính."],
  ["dailyv-household", "B1", "household", "/ˈhaʊshoʊld/", "hộ gia đình; việc nhà", "We share the household chores equally.", "Chúng tôi chia đều việc nhà."],
  ["dailyv-laundry", "B1", "laundry", "/ˈlɔːndri/", "quần áo cần giặt; việc giặt", "I usually do the laundry on Saturday.", "Tôi thường giặt đồ vào thứ Bảy."],
  ["dailyv-local", "B1", "local", "/ˈloʊkəl/", "địa phương", "We buy vegetables at the local market.", "Chúng tôi mua rau ở chợ địa phương."],
  ["dailyv-meal", "B1", "meal", "/miːl/", "bữa ăn", "Breakfast is my most important meal.", "Bữa sáng là bữa ăn quan trọng nhất của tôi."],
  ["dailyv-neighbor", "B1", "neighbor", "/ˈneɪbər/", "hàng xóm", "Our neighbor helped us move the sofa.", "Người hàng xóm đã giúp chúng tôi chuyển ghế sofa."],
  ["dailyv-organize", "B1", "organize", "/ˈɔːrɡənaɪz/", "sắp xếp; tổ chức", "I need to organize my room this weekend.", "Tôi cần sắp xếp phòng vào cuối tuần này."],
  ["dailyv-queue", "B1", "queue", "/kjuː/", "hàng người chờ", "We waited in a queue for twenty minutes.", "Chúng tôi xếp hàng chờ hai mươi phút."],
  ["dailyv-receipt", "B1", "receipt", "/rɪˈsiːt/", "hóa đơn", "Keep the receipt in case you return the shirt.", "Hãy giữ hóa đơn phòng khi bạn trả lại áo."],
  ["dailyv-repair", "B1", "repair", "/rɪˈper/", "sửa chữa", "The mechanic repaired my bike quickly.", "Thợ máy đã sửa xe đạp của tôi nhanh chóng."],
  ["dailyv-rent", "B1", "rent", "/rent/", "thuê; tiền thuê", "They rent a small apartment near the station.", "Họ thuê một căn hộ nhỏ gần nhà ga."],
  ["dailyv-routine", "B1", "routine", "/ruːˈtiːn/", "thói quen thường ngày", "Exercise is part of my morning routine.", "Tập thể dục là một phần thói quen buổi sáng của tôi."],
  ["dailyv-share", "B1", "share", "/ʃer/", "chia sẻ; dùng chung", "I share a flat with two friends.", "Tôi ở chung căn hộ với hai người bạn."],
  ["dailyv-spend", "B1", "spend", "/spend/", "dành; tiêu", "I spend about an hour cooking each day.", "Tôi dành khoảng một giờ nấu ăn mỗi ngày."],
  ["dailyv-store", "B1", "store", "/stɔːr/", "cửa hàng; cất giữ", "This store stays open until ten.", "Cửa hàng này mở cửa đến mười giờ."],
  ["dailyv-waste", "B1", "waste", "/weɪst/", "lãng phí; rác thải", "Do not waste food or clean water.", "Đừng lãng phí thức ăn hoặc nước sạch."],

  // Học tập và khóa học
  ["studyv-assignment", "B1", "assignment", "/əˈsaɪnmənt/", "bài tập được giao", "Our writing assignment is due on Friday.", "Bài tập viết của chúng tôi đến hạn vào thứ Sáu."],
  ["studyv-attend", "B1", "attend", "/əˈtend/", "tham dự", "All students should attend the review session.", "Tất cả học viên nên tham dự buổi ôn tập."],
  ["studyv-concentrate", "B1", "concentrate", "/ˈkɑːnsəntreɪt/", "tập trung", "I cannot concentrate when the room is noisy.", "Tôi không thể tập trung khi căn phòng ồn."],
  ["studyv-course", "B1", "course", "/kɔːrs/", "khóa học", "This course focuses on practical communication.", "Khóa học này tập trung vào giao tiếp thực tế."],
  ["studyv-deadline", "B1", "deadline", "/ˈdedlaɪn/", "hạn chót", "The deadline for the project is next Monday.", "Hạn chót của dự án là thứ Hai tới."],
  ["studyv-exam", "B1", "exam", "/ɪɡˈzæm/", "kỳ thi", "She is preparing for her B1 exam.", "Cô ấy đang chuẩn bị cho kỳ thi B1."],
  ["studyv-feedback", "B1", "feedback", "/ˈfiːdbæk/", "phản hồi", "The teacher gave useful feedback on my speaking.", "Giáo viên đưa ra phản hồi hữu ích về phần nói của tôi."],
  ["studyv-grade", "B1", "grade", "/ɡreɪd/", "điểm; xếp loại", "He received a good grade for his essay.", "Anh ấy nhận được điểm tốt cho bài luận."],
  ["studyv-instruction", "B1", "instruction", "/ɪnˈstrʌkʃən/", "hướng dẫn", "Read each instruction before answering.", "Hãy đọc từng hướng dẫn trước khi trả lời."],
  ["studyv-knowledge", "B1", "knowledge", "/ˈnɑːlɪdʒ/", "kiến thức", "The quiz tests your grammar knowledge.", "Bài kiểm tra đánh giá kiến thức ngữ pháp của bạn."],
  ["studyv-lecture", "B1", "lecture", "/ˈlektʃər/", "bài giảng", "I took notes during the lecture.", "Tôi đã ghi chú trong bài giảng."],
  ["studyv-note-taking", "B1", "note-taking", "/ˈnoʊt teɪkɪŋ/", "việc ghi chép", "Good note-taking helps you remember key ideas.", "Ghi chép tốt giúp bạn nhớ các ý chính."],
  ["studyv-pass", "B1", "pass", "/pæs/", "đỗ; vượt qua", "You need sixty points to pass the test.", "Bạn cần sáu mươi điểm để vượt qua bài kiểm tra."],
  ["studyv-prepare", "B1", "prepare", "/prɪˈper/", "chuẩn bị", "Prepare three examples before the lesson.", "Hãy chuẩn bị ba ví dụ trước buổi học."],
  ["studyv-research", "B1", "research", "/ˈriːsɜːrtʃ/", "nghiên cứu", "We did some research for our presentation.", "Chúng tôi đã nghiên cứu cho bài thuyết trình."],
  ["studyv-revise", "B1", "revise", "/rɪˈvaɪz/", "ôn tập; chỉnh sửa", "I revise new words every evening.", "Tôi ôn từ mới mỗi tối."],
  ["studyv-skill", "B1", "skill", "/skɪl/", "kỹ năng", "Listening is a skill that improves with practice.", "Nghe là kỹ năng tiến bộ nhờ luyện tập."],
  ["studyv-solve", "B1", "solve", "/sɑːlv/", "giải quyết", "Work with a partner to solve the problem.", "Hãy làm cùng bạn học để giải quyết vấn đề."],
  ["studyv-subject", "B1", "subject", "/ˈsʌbdʒɪkt/", "môn học; chủ đề", "English was my favorite subject at school.", "Tiếng Anh là môn yêu thích của tôi ở trường."],
  ["studyv-submit", "B1", "submit", "/səbˈmɪt/", "nộp", "Please submit your homework online.", "Vui lòng nộp bài tập về nhà trực tuyến."],
  ["studyv-task", "B1", "task", "/tæsk/", "nhiệm vụ; bài tập", "Complete the speaking task in two minutes.", "Hãy hoàn thành bài nói trong hai phút."],
  ["studyv-textbook", "B1", "textbook", "/ˈtekstbʊk/", "sách giáo khoa", "The examples are on page forty of the textbook.", "Các ví dụ ở trang bốn mươi của sách giáo khoa."],
  ["studyv-understand", "B1", "understand", "/ˌʌndərˈstænd/", "hiểu", "Ask a question if you do not understand.", "Hãy đặt câu hỏi nếu bạn không hiểu."],
  ["studyv-presentation", "B1", "presentation", "/ˌprezənˈteɪʃən/", "bài thuyết trình", "Our group gave a short presentation in English.", "Nhóm chúng tôi đã thuyết trình ngắn bằng tiếng Anh."],

  // Công việc
  ["workv-apply", "B1", "apply", "/əˈplaɪ/", "ứng tuyển; áp dụng", "I plan to apply for that position.", "Tôi dự định ứng tuyển vị trí đó."],
  ["workv-career", "B1", "career", "/kəˈrɪr/", "sự nghiệp", "She wants a career in digital marketing.", "Cô ấy muốn theo sự nghiệp tiếp thị số."],
  ["workv-colleague", "B1", "colleague", "/ˈkɑːliːɡ/", "đồng nghiệp", "A colleague helped me prepare the report.", "Một đồng nghiệp đã giúp tôi chuẩn bị báo cáo."],
  ["workv-customer", "B1", "customer", "/ˈkʌstəmər/", "khách hàng", "The customer asked for more information.", "Khách hàng yêu cầu thêm thông tin."],
  ["workv-department", "B1", "department", "/dɪˈpɑːrtmənt/", "phòng ban", "She works in the sales department.", "Cô ấy làm việc ở phòng kinh doanh."],
  ["workv-duty", "B1", "duty", "/ˈduːti/", "nhiệm vụ; trách nhiệm", "One of my duties is answering emails.", "Một nhiệm vụ của tôi là trả lời email."],
  ["workv-employee", "B1", "employee", "/ɪmˈplɔɪiː/", "nhân viên", "Every employee receives safety training.", "Mỗi nhân viên đều được đào tạo an toàn."],
  ["workv-employer", "B1", "employer", "/ɪmˈplɔɪər/", "người sử dụng lao động", "The employer offers flexible working hours.", "Công ty cung cấp giờ làm việc linh hoạt."],
  ["workv-interview", "B1", "interview", "/ˈɪntərvjuː/", "buổi phỏng vấn", "My job interview starts at nine.", "Buổi phỏng vấn việc làm của tôi bắt đầu lúc chín giờ."],
  ["workv-meeting", "B1", "meeting", "/ˈmiːtɪŋ/", "cuộc họp", "We discussed the budget in the meeting.", "Chúng tôi đã thảo luận ngân sách trong cuộc họp."],
  ["workv-office", "B1", "office", "/ˈɔːfɪs/", "văn phòng", "Our office is close to the city center.", "Văn phòng của chúng tôi gần trung tâm thành phố."],
  ["workv-profession", "B1", "profession", "/prəˈfeʃən/", "nghề nghiệp", "Teaching is a rewarding profession.", "Dạy học là một nghề đáng trân trọng."],
  ["workv-project", "B1", "project", "/ˈprɑːdʒekt/", "dự án", "The team finished the project early.", "Nhóm đã hoàn thành dự án sớm."],
  ["workv-promotion", "B1", "promotion", "/prəˈmoʊʃən/", "sự thăng chức", "He received a promotion after two years.", "Anh ấy được thăng chức sau hai năm."],
  ["workv-report", "B1", "report", "/rɪˈpɔːrt/", "báo cáo", "Please send the monthly report by Friday.", "Vui lòng gửi báo cáo tháng trước thứ Sáu."],
  ["workv-salary", "B1", "salary", "/ˈsæləri/", "lương", "The job offers a competitive salary.", "Công việc có mức lương cạnh tranh."],
  ["workv-schedule", "B1", "schedule", "/ˈskedʒuːl/", "lịch trình", "Check the schedule before booking a meeting.", "Hãy kiểm tra lịch trước khi đặt cuộc họp."],
  ["workv-shift", "B1", "shift", "/ʃɪft/", "ca làm việc", "I am working the evening shift this week.", "Tuần này tôi làm ca tối."],
  ["workv-staff", "B1", "staff", "/stæf/", "nhân sự", "The hotel staff were friendly and helpful.", "Nhân viên khách sạn thân thiện và nhiệt tình."],
  ["workv-teamwork", "B1", "teamwork", "/ˈtiːmwɜːrk/", "làm việc nhóm", "Good teamwork made the event successful.", "Làm việc nhóm tốt đã giúp sự kiện thành công."],
  ["workv-training", "B1", "training", "/ˈtreɪnɪŋ/", "đào tạo", "New staff attend two days of training.", "Nhân viên mới tham gia hai ngày đào tạo."],
  ["workv-vacancy", "B1", "vacancy", "/ˈveɪkənsi/", "vị trí tuyển dụng", "I saw a vacancy for a sales assistant.", "Tôi thấy một vị trí tuyển trợ lý bán hàng."],
  ["workv-workload", "B1", "workload", "/ˈwɜːrkloʊd/", "khối lượng công việc", "My workload is heavier at the end of the month.", "Khối lượng công việc của tôi nặng hơn vào cuối tháng."],
  ["workv-workplace", "B1", "workplace", "/ˈwɜːrkpleɪs/", "nơi làm việc", "Respect is important in every workplace.", "Sự tôn trọng quan trọng ở mọi nơi làm việc."],

  // Du lịch
  ["travelv-accommodation", "B1", "accommodation", "/əˌkɑːməˈdeɪʃən/", "chỗ ở", "We found affordable accommodation near the beach.", "Chúng tôi tìm được chỗ ở vừa túi tiền gần bãi biển."],
  ["travelv-book", "B1", "book", "/bʊk/", "đặt chỗ", "You should book your room in advance.", "Bạn nên đặt phòng trước."],
  ["travelv-border", "B1", "border", "/ˈbɔːrdər/", "biên giới", "We showed our passports at the border.", "Chúng tôi xuất trình hộ chiếu tại biên giới."],
  ["travelv-delay", "B1", "delay", "/dɪˈleɪ/", "sự trì hoãn; chậm chuyến", "The flight left after a two-hour delay.", "Chuyến bay khởi hành sau khi chậm hai giờ."],
  ["travelv-destination", "B1", "destination", "/ˌdestəˈneɪʃən/", "điểm đến", "Da Nang is a popular holiday destination.", "Đà Nẵng là một điểm nghỉ dưỡng phổ biến."],
  ["travelv-direction", "B1", "direction", "/dəˈrekʃən/", "phương hướng; chỉ dẫn", "A local person gave us clear directions.", "Một người địa phương đã chỉ đường rõ ràng cho chúng tôi."],
  ["travelv-flight", "B1", "flight", "/flaɪt/", "chuyến bay", "Our flight arrives at six in the morning.", "Chuyến bay của chúng tôi đến lúc sáu giờ sáng."],
  ["travelv-foreign", "B1", "foreign", "/ˈfɔːrən/", "nước ngoài", "It is useful to learn phrases before visiting a foreign country.", "Học các cụm từ trước khi đến một nước ngoài rất hữu ích."],
  ["travelv-journey", "B1", "journey", "/ˈdʒɜːrni/", "hành trình", "The train journey took about four hours.", "Hành trình bằng tàu mất khoảng bốn giờ."],
  ["travelv-luggage", "B1", "luggage", "/ˈlʌɡɪdʒ/", "hành lý", "My luggage was too heavy to carry.", "Hành lý của tôi quá nặng để mang."],
  ["travelv-passenger", "B1", "passenger", "/ˈpæsəndʒər/", "hành khách", "Passengers should remain in their seats.", "Hành khách nên ngồi yên tại chỗ."],
  ["travelv-passport", "B1", "passport", "/ˈpæspɔːrt/", "hộ chiếu", "Check that your passport is still valid.", "Hãy kiểm tra hộ chiếu của bạn còn hiệu lực."],
  ["travelv-platform", "B1", "platform", "/ˈplætfɔːrm/", "sân ga", "The train leaves from platform five.", "Tàu khởi hành từ sân ga số năm."],
  ["travelv-reservation", "B1", "reservation", "/ˌrezərˈveɪʃən/", "đặt chỗ", "I have a reservation under the name Nguyen.", "Tôi có đặt chỗ dưới tên Nguyễn."],
  ["travelv-route", "B1", "route", "/ruːt/", "tuyến đường", "This bus route goes through the old town.", "Tuyến xe buýt này đi qua phố cổ."],
  ["travelv-sightseeing", "B1", "sightseeing", "/ˈsaɪtsiːɪŋ/", "tham quan", "We spent the afternoon sightseeing.", "Chúng tôi dành buổi chiều để tham quan."],
  ["travelv-station", "B1", "station", "/ˈsteɪʃən/", "nhà ga", "The hotel is a short walk from the station.", "Khách sạn cách nhà ga một quãng đi bộ ngắn."],
  ["travelv-suitcase", "B1", "suitcase", "/ˈsuːtkeɪs/", "va-li", "I packed a light jacket in my suitcase.", "Tôi đã xếp một chiếc áo khoác nhẹ vào va-li."],
  ["travelv-ticket", "B1", "ticket", "/ˈtɪkɪt/", "vé", "You can buy a ticket from the machine.", "Bạn có thể mua vé từ máy bán vé."],
  ["travelv-tour", "B1", "tour", "/tʊr/", "chuyến tham quan", "We joined a walking tour of the city.", "Chúng tôi tham gia chuyến tham quan thành phố bằng đi bộ."],
  ["travelv-traffic", "B1", "traffic", "/ˈtræfɪk/", "giao thông", "Leave early because the traffic is heavy.", "Hãy đi sớm vì giao thông đông."],
  ["travelv-transport", "B1", "transport", "/ˈtrænspɔːrt/", "phương tiện giao thông", "Public transport is cheap and reliable here.", "Giao thông công cộng ở đây rẻ và đáng tin cậy."],
  ["travelv-trip", "B1", "trip", "/trɪp/", "chuyến đi", "We are planning a weekend trip to Hue.", "Chúng tôi đang lên kế hoạch đi Huế cuối tuần."],
  ["travelv-vehicle", "B1", "vehicle", "/ˈviːəkəl/", "phương tiện", "Electric vehicles are becoming more common.", "Phương tiện điện đang trở nên phổ biến hơn."],

  // Giao tiếp và quan hệ
  ["socialv-agree", "B1", "agree", "/əˈɡriː/", "đồng ý", "I agree with your point about public transport.", "Tôi đồng ý với ý kiến của bạn về giao thông công cộng."],
  ["socialv-apologize", "B1", "apologize", "/əˈpɑːlədʒaɪz/", "xin lỗi", "You should apologize for arriving late.", "Bạn nên xin lỗi vì đến muộn."],
  ["socialv-argue", "B1", "argue", "/ˈɑːrɡjuː/", "tranh luận", "They sometimes argue about small things.", "Đôi khi họ tranh luận về những chuyện nhỏ."],
  ["socialv-celebrate", "B1", "celebrate", "/ˈseləbreɪt/", "ăn mừng", "We went out to celebrate her new job.", "Chúng tôi ra ngoài ăn mừng công việc mới của cô ấy."],
  ["socialv-communicate", "B1", "communicate", "/kəˈmjuːnəkeɪt/", "giao tiếp", "Good teams communicate clearly and often.", "Nhóm tốt giao tiếp rõ ràng và thường xuyên."],
  ["socialv-complain", "B1", "complain", "/kəmˈpleɪn/", "phàn nàn", "The customer complained about the slow service.", "Khách hàng phàn nàn về dịch vụ chậm."],
  ["socialv-contact", "B1", "contact", "/ˈkɑːntækt/", "liên hệ", "Contact me if you need any help.", "Hãy liên hệ với tôi nếu bạn cần giúp đỡ."],
  ["socialv-conversation", "B1", "conversation", "/ˌkɑːnvərˈseɪʃən/", "cuộc trò chuyện", "We had an interesting conversation about travel.", "Chúng tôi có một cuộc trò chuyện thú vị về du lịch."],
  ["socialv-disagree", "B1", "disagree", "/ˌdɪsəˈɡriː/", "không đồng ý", "It is okay to disagree politely.", "Không đồng ý một cách lịch sự là điều bình thường."],
  ["socialv-discuss", "B1", "discuss", "/dɪˈskʌs/", "thảo luận", "Let's discuss the problem after lunch.", "Hãy thảo luận vấn đề sau bữa trưa."],
  ["socialv-encourage", "B1", "encourage", "/ɪnˈkɜːrɪdʒ/", "khuyến khích", "My teacher encouraged me to speak more.", "Giáo viên khuyến khích tôi nói nhiều hơn."],
  ["socialv-friendship", "B1", "friendship", "/ˈfrendʃɪp/", "tình bạn", "Their friendship began at university.", "Tình bạn của họ bắt đầu ở trường đại học."],
  ["socialv-greet", "B1", "greet", "/ɡriːt/", "chào hỏi", "She greeted every guest with a smile.", "Cô ấy chào mỗi vị khách bằng một nụ cười."],
  ["socialv-introduce", "B1", "introduce", "/ˌɪntrəˈduːs/", "giới thiệu", "Let me introduce you to my colleague.", "Để tôi giới thiệu bạn với đồng nghiệp của tôi."],
  ["socialv-invite", "B1", "invite", "/ɪnˈvaɪt/", "mời", "They invited us to dinner on Saturday.", "Họ mời chúng tôi ăn tối vào thứ Bảy."],
  ["socialv-joke", "B1", "joke", "/dʒoʊk/", "trò đùa", "He told a funny joke during the break.", "Anh ấy kể một câu đùa vui trong giờ nghỉ."],
  ["socialv-kindness", "B1", "kindness", "/ˈkaɪndnəs/", "lòng tốt", "I will always remember her kindness.", "Tôi sẽ luôn nhớ lòng tốt của cô ấy."],
  ["socialv-message", "B1", "message", "/ˈmesɪdʒ/", "tin nhắn", "Leave me a message when you arrive.", "Hãy để lại tin nhắn khi bạn đến."],
  ["socialv-polite", "B1", "polite", "/pəˈlaɪt/", "lịch sự", "It is polite to say thank you.", "Nói cảm ơn là lịch sự."],
  ["socialv-promise", "B1", "promise", "/ˈprɑːmɪs/", "lời hứa; hứa", "I promise to call you after work.", "Tôi hứa sẽ gọi cho bạn sau giờ làm."],
  ["socialv-refuse", "B1", "refuse", "/rɪˈfjuːz/", "từ chối", "He politely refused the invitation.", "Anh ấy lịch sự từ chối lời mời."],
  ["socialv-respond", "B1", "respond", "/rɪˈspɑːnd/", "phản hồi", "Please respond to the email by tomorrow.", "Vui lòng phản hồi email trước ngày mai."],
  ["socialv-trust", "B1", "trust", "/trʌst/", "tin tưởng", "It takes time to build trust.", "Cần thời gian để xây dựng lòng tin."],
  ["socialv-welcome", "B1", "welcome", "/ˈwelkəm/", "chào đón", "They welcomed us into their home.", "Họ chào đón chúng tôi vào nhà."],

  // Sức khỏe và lối sống
  ["healthv-ache", "B1", "ache", "/eɪk/", "cơn đau âm ỉ", "My legs ache after the long walk.", "Chân tôi đau sau chuyến đi bộ dài."],
  ["healthv-active", "B1", "active", "/ˈæktɪv/", "năng động", "Staying active is good for your heart.", "Duy trì vận động tốt cho tim của bạn."],
  ["healthv-advice", "B1", "advice", "/ədˈvaɪs/", "lời khuyên", "The doctor gave me some useful advice.", "Bác sĩ cho tôi một số lời khuyên hữu ích."],
  ["healthv-balance", "B1", "balance", "/ˈbæləns/", "sự cân bằng", "A healthy life needs a balance between work and rest.", "Cuộc sống lành mạnh cần cân bằng giữa làm việc và nghỉ ngơi."],
  ["healthv-breathe", "B1", "breathe", "/briːð/", "thở", "Breathe slowly when you feel nervous.", "Hãy thở chậm khi bạn thấy lo lắng."],
  ["healthv-check-up", "B1", "check-up", "/ˈtʃek ʌp/", "buổi khám sức khỏe", "I have a dental check-up twice a year.", "Tôi khám răng hai lần một năm."],
  ["healthv-cough", "B1", "cough", "/kɔːf/", "ho; cơn ho", "He stayed home because of a bad cough.", "Anh ấy ở nhà vì bị ho nặng."],
  ["healthv-diet", "B1", "diet", "/ˈdaɪət/", "chế độ ăn", "A balanced diet includes plenty of vegetables.", "Chế độ ăn cân bằng bao gồm nhiều rau."],
  ["healthv-exercise", "B1", "exercise", "/ˈeksərsaɪz/", "tập thể dục", "Regular exercise improves your mood.", "Tập thể dục thường xuyên cải thiện tâm trạng."],
  ["healthv-fit", "B1", "fit", "/fɪt/", "khỏe mạnh; cân đối", "Cycling helps me keep fit.", "Đạp xe giúp tôi giữ dáng khỏe mạnh."],
  ["healthv-headache", "B1", "headache", "/ˈhedeɪk/", "đau đầu", "Too much screen time gives me a headache.", "Nhìn màn hình quá lâu khiến tôi đau đầu."],
  ["healthv-healthy", "B1", "healthy", "/ˈhelθi/", "lành mạnh; khỏe mạnh", "We try to cook healthy meals at home.", "Chúng tôi cố nấu các bữa ăn lành mạnh tại nhà."],
  ["healthv-illness", "B1", "illness", "/ˈɪlnəs/", "bệnh tật", "The illness kept her away from work for a week.", "Căn bệnh khiến cô ấy nghỉ làm một tuần."],
  ["healthv-medicine", "B1", "medicine", "/ˈmedɪsən/", "thuốc", "Take this medicine after meals.", "Hãy uống thuốc này sau bữa ăn."],
  ["healthv-pain", "B1", "pain", "/peɪn/", "cơn đau", "I felt a sharp pain in my shoulder.", "Tôi cảm thấy đau nhói ở vai."],
  ["healthv-recover", "B1", "recover", "/rɪˈkʌvər/", "hồi phục", "It took him a month to recover fully.", "Anh ấy mất một tháng để hồi phục hoàn toàn."],
  ["healthv-relax", "B1", "relax", "/rɪˈlæks/", "thư giãn", "Music helps me relax after a busy day.", "Âm nhạc giúp tôi thư giãn sau một ngày bận rộn."],
  ["healthv-rest", "B1", "rest", "/rest/", "nghỉ ngơi", "You need to rest if you feel tired.", "Bạn cần nghỉ ngơi nếu cảm thấy mệt."],
  ["healthv-sleep", "B1", "sleep", "/sliːp/", "giấc ngủ; ngủ", "Most adults need seven or eight hours of sleep.", "Hầu hết người lớn cần ngủ bảy hoặc tám giờ."],
  ["healthv-stress", "B1", "stress", "/stres/", "căng thẳng", "Planning ahead can reduce stress.", "Lên kế hoạch trước có thể giảm căng thẳng."],
  ["healthv-symptom", "B1", "symptom", "/ˈsɪmptəm/", "triệu chứng", "A high temperature can be a symptom of infection.", "Sốt cao có thể là triệu chứng nhiễm trùng."],
  ["healthv-treatment", "B1", "treatment", "/ˈtriːtmənt/", "sự điều trị", "The treatment helped her feel better.", "Việc điều trị giúp cô ấy cảm thấy khỏe hơn."],
  ["healthv-tired", "B1", "tired", "/ˈtaɪərd/", "mệt mỏi", "I feel tired when I do not sleep enough.", "Tôi thấy mệt khi không ngủ đủ."],
  ["healthv-well", "B1", "well", "/wel/", "khỏe; tốt", "She was ill yesterday but feels well today.", "Hôm qua cô ấy bị ốm nhưng hôm nay thấy khỏe." ]
];
