export const EXAMPLE_AMERICAN_IPA: Readonly<Record<string, string>> = {
  "make-progress": "/aɪ meɪk prˈɑːɡrɛs wɛn aɪ prˈæktɪs ˈɛvri deɪ/",
  "take-a-break": "/lɛts teɪk ə ʃɔːrt breɪk/",
  "figure-out": "/aɪ niːd tə fˈɪɡjɚ aʊt haʊ ðɪs wɜːks/",
  "be-used-to": "/aɪ æm juːzd tə ɡˈɛɾɪŋ ʌp ˈɜːli/",
  "look-forward-to": "/aɪ lʊk fˈɔːrwɚd tə hˈɪrɪŋ frʌm juː/",
  "in-advance": "/pliːz bʊk jʊr tˈɪkɪt ɪn ədvˈæns/",
  "on-time": "/ðə mˈiːɾɪŋ stɑːrɾɪd ɔn taɪm/",
  "instead-of": "/traɪ wˈɔːkɪŋ ɪnstˈɛd əv drˈaɪvɪŋ/",
  "according-to": "/əkˈɔːrdɪŋ tə ðə rɪpɔːrt seɪlz ɪŋkrˈiːst/",
  "as-a-result": "/ɪt reɪnd hˈɛvili əz ə rɪzˈʌlt ðə mætʃ wʌz kˈænsəld/",
  "deal-with": "/ʃiː noʊz haʊ tə diːl wɪð dˈɪfɪkəlt kˈʌstəmɚz/",
  "depend-on": "/səksˈɛs dɪpɛndz ɔn kənsˈɪstənt prˈæktɪs/",
  "get-along": "/aɪ ɡɛt əlˈɔŋ wɛl wɪð maɪ kˈɑːliːɡz/",
  "keep-in-mind": "/kiːp ɪn maɪnd ðæt ðə dˈɛdlaɪn ɪz frˈaɪdeɪ/",
  "make-sense": "/jʊr ɛksplənˈeɪʃən meɪks sɛns/",
  "pay-attention": "/peɪ ətˈɛnʃən tə ðə fˈaɪnəl saʊnd/",
  "run-out-of": "/wiː hæv rʌn aʊt əv mɪlk/",
  "take-part-in": "/mˈɛni stˈuːdənts tʊk pɑːrt ɪn ðə kˌɑːmpətˈɪʃən/",
  "used-to": "/aɪ juːst tə lɪv nɪr ðə biːtʃ/",
  "work-out": "/wiː kæn wɜːk aʊt ə səlˈuːʃən təɡˈɛðɚ/",
  "available": "/ɪz ðɪs siːt əvˈeɪləbəl/",
  "confident": "/ʃiː fiːlz kˈɑːnfɪdənt əbˈaʊt ðə ˈɪntɚvjˌuː/",
  "convenient": "/ˈɑːnlaɪn bˈæŋkɪŋ ɪz kənvˈiːnɪənt fər bˈɪzi pˈiːpəl/",
  "effective": "/ðɪs ɪz ən ɪfˈɛktɪv weɪ tə lɜːn voʊkˈæbjʊlˌɛri/",
  "improve": "/rˈiːdɪŋ dˈeɪli kæn ɪmprˈuːv jʊr voʊkˈæbjʊlˌɛri/",
  "opportunity": "/ðɪs dʒɑːb ɪz ə ɡreɪt ɑːpɚtˈuːnɪɾi/",
  "recommend": "/aɪ rˌɛkəmˈɛnd prˈæktɪsɪŋ wɪð ʃɔːrt sˈɛntənsɪz/",
  "responsible": "/ʃiː ɪz rɪspˈɑːnsɪbəl fər ðə wˈiːkli rɪpɔːrt/",
  "although": "/ɔːlðˈoʊ ɪt wʌz leɪt hiː kɛpt stˈʌdiɪŋ/",
  "unless": "/juː woʊnt ɪmprˈuːv ʌnlˈɛs juː prˈæktɪs/",
  "would-rather": "/aɪ wʊd rˈæðɚ stˈʌdi ɪn ðə mˈɔːrnɪŋ/",
  "could-you": "/kʊd juː seɪ ðæt əɡˈɛn mɔːr slˈoʊli/",
  "what-do-you-mean": "/wʌt duː juː miːn baɪ prˈæktɪkəl ˈɪŋɡlɪʃ/",
  "sounds-good": "/lɛts miːt ət sˈɛvən ðæt saʊndz ɡʊd/",
  "not-sure": "/aɪm nɑːt ʃʊr bʌt aɪ kæn tʃɛk/",
  "it-depends": "/ɪt dɪpɛndz ɔn haʊ mʌtʃ taɪm wiː hæv/",
  "in-my-opinion": "/ɪn maɪ əpˈɪniən pˈʌblɪk trˈænspɔːrt ʃʊd biː tʃˈiːpɚ/",
  "for-example": "/juː kæn prˈæktɪs ˈɛnɪwˌɛr fər ɛɡzˈæmpəl ɔn ðə bʌs/",
  "however": "/ðə tæsk wʌz dˈɪfɪkəlt haʊˈɛvɚ wiː kəmplˈiːɾɪd ɪt/",
  "therefore": "/ðə roʊd wʌz kloʊzd ðˈɛrfɔːr wiː tʊk ənˈʌðɚ raʊt/",
  "im-down": "/aɪm daʊn fər ə kwɪk ˈɪŋɡlɪʃ ɡeɪm/",
  "low-key": "/aɪm lˈoʊkˈiː ɛksˈaɪɾɪd əbˈaʊt ðə trɪp/",
  "good-vibe": "/ðɪs kæfˈeɪ hæz ə ɡʊd vaɪb/",
  "no-big-deal": "/θæŋks fər hˈɛlpɪŋ miː noʊ bɪɡ diːl/",
  "thats-on-me": "/aɪ mɪst ðə dˈɛdlaɪn ən ðæts ɔn miː/",
  "legit": "/ðæt prənˌʌnsɪˈeɪʃən tɪp ɪz lədʒˈɪt jˈuːsfəl/",
  "corev-achieve": "/ʃiː wɜːkt hɑːrd tə ətʃˈiːv hɜː ɡoʊl/",
  "corev-advantage": "/ˈɑːnlaɪn lˈɛsənz hæv ðə ədvˈæntɪdʒ əv flˌɛksəbˈɪlɪɾi/",
  "corev-avoid": "/traɪ tə əvˈɔɪd jˈuːzɪŋ jʊr foʊn waɪl stˈʌdiɪŋ/",
  "corev-behave": "/ðə tʃˈɪldrən bɪheɪvd wɛl dˈʊrrɪŋ ðə trɪp/",
  "corev-challenge": "/lˈɜːnɪŋ tə spiːk kˈɑːnfɪdəntli ɪz ə tʃˈælɪndʒ/",
  "corev-choice": "/juː hæv ə tʃɔɪs bɪtwiːn tuː kɔːrsɪz/",
  "corev-compare": "/kəmpˈɛr ðə tuː pˈɪktʃɚz ən faɪnd θriː dˈɪfrənsɪz/",
  "corev-consider": "/wiː ɑːr kənsˈɪdɚrɪŋ mˈuːvɪŋ tə ə kwˈaɪəɾɚ ˈɛriə/",
  "corev-decision": "/ɪt wʌz ə dˈɪfɪkəlt dɪsˈɪʒən tə meɪk/",
  "corev-describe": "/kæn juː dɪskraɪb ðə pˈɜːsən juː mɛt/",
  "corev-develop": "/rˈiːdɪŋ hɛlps juː dɪvˈɛləp ə wˈaɪdɚ voʊkˈæbjʊlˌɛri/",
  "corev-difference": "/ðɛr ɪz ə bɪɡ dˈɪfrəns bɪtwiːn nˈoʊɪŋ ən jˈuːzɪŋ ə wɜːd/",
  "corev-experience": "/wˈɜːkɪŋ əbrˈɔːd wʌz ə vˈæljuːəbəl ɛkspˈiərɪəns/",
  "corev-explain": "/pliːz ɛksplˈeɪn ðə ruːl ɪn jʊr oʊn wɜːdz/",
  "corev-include": "/ðə praɪs ɪŋklˈuːdz brˈɛkfəst ən wˈaɪfˌaɪ/",
  "corev-increase": "/ˈdeɪli ˈpræktɪs kən ɪnˈkriːs jʊr ˈkɑːnfɪdəns/",
  "corev-influence": "/frɛndz kæn ˈɪnfluːəns ðə tʃɔɪsɪz wiː meɪk/",
  "corev-manage": "/aɪ mˈænɪdʒd tə fˈɪnɪʃ ðə tæsk ɔn taɪm/",
  "corev-provide": "/ðə wˈɛbsaɪt prəvˈaɪdz jˈuːsfəl lˈɜːnɪŋ mətˈɪriəlz/",
  "corev-reason": "/wʌt ɪz ðə meɪn rˈiːzən fər jʊr tʃɔɪs/",
  "corev-reduce": "/wˈɔːkɪŋ mɔːr kæn rɪduːs strɛs/",
  "corev-suggest": "/aɪ sədʒˈɛst tˈeɪkɪŋ ə ʃɔːrt breɪk/",
  "corev-support": "/maɪ fˈæmɪli səpˈɔːrts maɪ dɪsˈɪʒən tə stˈʌdi əbrˈɔːd/",
  "corev-succeed": "/juː wɪl səksˈiːd ɪf juː kiːp prˈæktɪsɪŋ/",
  "dailyv-appointment": "/aɪ hæv ə dˈɛntɪst əpˈɔɪntmənt təmˈɑːroʊ mˈɔːrnɪŋ/",
  "dailyv-borrow": "/kʊd aɪ bˈɑːroʊ jʊr tʃˈɑːrdʒɚ fər ən ˈaʊɚ/",
  "dailyv-cancel": "/wiː hæd tə kˈænsəl dˈɪnɚ bɪkˈʌz əv ðə stɔːrm/",
  "dailyv-clean-up": "/lɛts kliːn ʌp ðə kˈɪtʃən ˈæftɚ dˈɪnɚ/",
  "dailyv-comfortable": "/ðiːz ʃuːz ɑːr kˈʌmftəbəl ɪnˈʌf fər wˈɔːkɪŋ/",
  "dailyv-crowded": "/ðə sˈuːpɚmˌɑːrkɪt ɪz jˈuːʒuːəli kraʊdɪd ɔn sˈʌndeɪ/",
  "dailyv-decide": "/wiː niːd tə dɪsaɪd wʌt tə kʊk tənˈaɪt/",
  "dailyv-deliver": "/ðeɪ wɪl dɪlˈɪvɚ ðə tˈeɪbəl ðɪs ˌæftɚnˈuːn/",
  "dailyv-entrance": "/miːt miː nɪr ðə meɪn ˈɛntrəns/",
  "dailyv-household": "/wiː ʃɛr ðə hˈaʊshoʊld tʃɔːrz ˈiːkwəli/",
  "dailyv-laundry": "/aɪ jˈuːʒuːəli duː ðə lˈɔːndri ɔn sˈæɾɚdˌeɪ/",
  "dailyv-local": "/wiː baɪ vˈɛdʒɪɾəbəlz ət ðə lˈoʊkəl mˈɑːrkɪt/",
  "dailyv-meal": "/brˈɛkfəst ɪz maɪ moʊst ɪmpˈɔːrtənt miːl/",
  "dailyv-neighbor": "/ˌaʊɚ nˈeɪbɚ hɛlpt ʌs muːv ðə sˈoʊfə/",
  "dailyv-organize": "/aɪ niːd tə ˈɔːrɡənˌaɪz maɪ ruːm ðɪs wˈiːkɛnd/",
  "dailyv-queue": "/wiː weɪɾɪd ɪn ə kjuː fər twˈɛnti mˈɪnɪts/",
  "dailyv-receipt": "/kiːp ðə rɪsiːt ɪn keɪs juː rɪtɜːn ðə ʃɜːt/",
  "dailyv-repair": "/ðə mɪkˈænɪk rɪpɛrd maɪ baɪk kwˈɪkli/",
  "dailyv-rent": "/ðeɪ rɛnt ə smɔːl əpˈɑːrtmənt nɪr ðə stˈeɪʃən/",
  "dailyv-routine": "/ˈɛksɚsˌaɪz ɪz pɑːrt əv maɪ mˈɔːrnɪŋ ruːtˈiːn/",
  "dailyv-share": "/aɪ ʃɛr ə flæt wɪð tuː frɛndz/",
  "dailyv-spend": "/aɪ spɛnd əbˈaʊt ən ˈaʊɚ kˈʊkɪŋ iːtʃ deɪ/",
  "dailyv-store": "/ðɪs stɔːr steɪz ˈoʊpən ʌntˈɪl tɛn/",
  "dailyv-waste": "/duː nɑːt weɪst fuːd ər kliːn wˈɔːɾɚ/",
  "studyv-assignment": "/ˌaʊɚ rˈaɪɾɪŋ əsˈaɪnmənt ɪz duː ɔn frˈaɪdeɪ/",
  "studyv-attend": "/ɔːl stˈuːdənts ʃʊd ətˈɛnd ðə rɪvjuː sˈɛʃən/",
  "studyv-concentrate": "/aɪ kænˈɑːt kˈɑːnsəntrˌeɪt wɛn ðə ruːm ɪz nˈɔɪzi/",
  "studyv-course": "/ðɪs kɔːrs fˈoʊkəsɪz ɔn prˈæktɪkəl kəmjˌuːnɪkˈeɪʃən/",
  "studyv-deadline": "/ðə dˈɛdlaɪn fər ðə prˈɑːdʒɛkt ɪz nɛkst mˈʌndeɪ/",
  "studyv-exam": "/ʃiː ɪz prɪpˈɛrɪŋ fɔːr hɜː bˈiː wˈʌn ɛɡzˈæm/",
  "studyv-feedback": "/ðə tˈiːtʃɚ ɡeɪv jˈuːsfəl fˈiːdbæk ɔn maɪ spˈiːkɪŋ/",
  "studyv-grade": "/hiː rɪsiːvd ə ɡʊd ɡreɪd fər hɪz ˈɛseɪ/",
  "studyv-instruction": "/riːd iːtʃ ɪnstrˈʌkʃən bɪfɔːr ˈænsɚrɪŋ/",
  "studyv-knowledge": "/ðə kwɪz tɛsts jʊr ɡrˈæmɚ nˈɑːlɪdʒ/",
  "studyv-lecture": "/aɪ tʊk noʊts dˈʊrrɪŋ ðə lˈɛktʃɚ/",
  "studyv-note-taking": "/ɡʊd nˈoʊttˈeɪkɪŋ hɛlps juː rɪmˈɛmbɚ kiː aɪdˈiəz/",
  "studyv-pass": "/juː niːd sˈɪksti pɔɪnts tə pæs ðə tɛst/",
  "studyv-prepare": "/prɪpˈɛr θriː ɛɡzˈæmpəlz bɪfɔːr ðə lˈɛsən/",
  "studyv-research": "/wiː dɪd sʌm rɪsɜːtʃ fər ˌaʊɚ prˌɛzəntˈeɪʃən/",
  "studyv-revise": "/aɪ rɪvaɪz nuː wɜːdz ˈɛvri ˈiːvnɪŋ/",
  "studyv-skill": "/lˈɪsənɪŋ ɪz ə skɪl ðæt ɪmprˈuːvz wɪð prˈæktɪs/",
  "studyv-solve": "/wɜːk wɪð ə pˈɑːrtnɚ tə sɑːlv ðə prˈɑːbləm/",
  "studyv-subject": "/ˈɪŋɡlɪʃ wʌz maɪ fˈeɪvɚrɪt sˈʌbdʒɛkt ət skuːl/",
  "studyv-submit": "/pliːz səbmˈɪt jʊr hˈoʊmwɜːk ˈɑːnlaɪn/",
  "studyv-task": "/kəmplˈiːt ðə spˈiːkɪŋ tæsk ɪn tuː mˈɪnɪts/",
  "studyv-textbook": "/ðə ɛɡzˈæmpəlz ɑːr ɔn peɪdʒ fˈɔːrɾi əv ðə tˈɛkstbʊk/",
  "studyv-understand": "/æsk ə kwˈɛstʃən ɪf juː duː nɑːt ˌʌndɚstˈænd/",
  "studyv-presentation": "/ˌaʊɚ ɡruːp ɡeɪv ə ʃɔːrt prˌɛzəntˈeɪʃən ɪn ˈɪŋɡlɪʃ/",
  "workv-apply": "/aɪ plæn tə əplˈaɪ fər ðæt pəzˈɪʃən/",
  "workv-career": "/ʃiː wɔnts ə kɚrˈɪr ɪn dˈɪdʒɪɾəl mˈɑːrkɪɾɪŋ/",
  "workv-colleague": "/ə kˈɑːliːɡ hɛlpt miː prɪpˈɛr ðə rɪpɔːrt/",
  "workv-customer": "/ðə kˈʌstəmɚ æskt fər mɔːr ˌɪnfɚmˈeɪʃən/",
  "workv-department": "/ʃiː wɜːks ɪn ðə seɪlz dɪpˈɑːrtmənt/",
  "workv-duty": "/wʌn əv maɪ dˈuːɾiz ɪz ˈænsɚrɪŋ ˈiːmeɪlz/",
  "workv-employee": "/ˈɛvri ɛmplˈɔɪiː rɪsiːvz sˈeɪfti trˈeɪnɪŋ/",
  "workv-employer": "/ðə ɛmplˈɔɪɚ ˈɔfɚz flˈɛksɪbəl wˈɜːkɪŋ ˈaʊɚz/",
  "workv-interview": "/maɪ dʒɑːb ˈɪntɚvjˌuː stɑːrts ət naɪn/",
  "workv-meeting": "/wiː dɪskˈʌst ðə bˈʌdʒɪt ɪn ðə mˈiːɾɪŋ/",
  "workv-office": "/ˌaʊɚ ˈɑːfɪs ɪz kloʊs tə ðə sˈɪɾi sˈɛntɚ/",
  "workv-profession": "/tˈiːtʃɪŋ ɪz ə rɪwˈɔːrdɪŋ prəfˈɛʃən/",
  "workv-project": "/ðə tiːm fˈɪnɪʃt ðə prˈɑːdʒɛkt ˈɜːli/",
  "workv-promotion": "/hiː rɪsiːvd ə prəmˈoʊʃən ˈæftɚ tuː jɪrz/",
  "workv-report": "/pliːz sɛnd ðə mˈʌnθli rɪpɔːrt baɪ frˈaɪdeɪ/",
  "workv-salary": "/ðə dʒɑːb ˈɔfɚz ə kəmpˈɛɾɪtˌɪv sˈælɚri/",
  "workv-schedule": "/tʃɛk ðə skˈɛdʒuːl bɪfɔːr bˈʊkɪŋ ə mˈiːɾɪŋ/",
  "workv-shift": "/aɪ æm wˈɜːkɪŋ ðə ˈiːvnɪŋ ʃɪft ðɪs wiːk/",
  "workv-staff": "/ðə hoʊtˈɛl stæf wɜː frˈɛndli ən hˈɛlpfəl/",
  "workv-teamwork": "/ɡʊd tˈiːmwɜːk meɪd ðə ɪvɛnt səksˈɛsfəl/",
  "workv-training": "/nuː stæf ətˈɛnd tuː deɪz əv trˈeɪnɪŋ/",
  "workv-vacancy": "/aɪ sɔː ə vˈeɪkənsi fər ə seɪlz əsˈɪstənt/",
  "workv-workload": "/maɪ wˈɜːkloʊd ɪz hˈɛviɚ ət ðə ɛnd əv ðə mʌnθ/",
  "workv-workplace": "/rɪspɛkt ɪz ɪmpˈɔːrtənt ɪn ˈɛvri wˈɜːkpleɪs/",
  "travelv-accommodation": "/wiː faʊnd əfˈɔːrdəbəl əkˌɑːmədˈeɪʃən nɪr ðə biːtʃ/",
  "travelv-book": "/juː ʃʊd bʊk jʊr ruːm ɪn ədvˈæns/",
  "travelv-border": "/wiː ʃoʊd ˌaʊɚ pˈæspɔːrts ət ðə bˈɔːrdɚ/",
  "travelv-delay": "/ðə flaɪt lɛft ˈæftɚ ə tˈuːˈaʊɚ dɪleɪ/",
  "travelv-destination": "/dɑː næŋ ɪz ə pˈɑːpjʊlɚ hˈɑːlɪdˌeɪ dˌɛstɪnˈeɪʃən/",
  "travelv-direction": "/ə lˈoʊkəl pˈɜːsən ɡeɪv ʌs klɪr dɪrˈɛkʃənz/",
  "travelv-flight": "/ˌaʊɚ flaɪt ɚrˈaɪvz ət sɪks ɪn ðə mˈɔːrnɪŋ/",
  "travelv-foreign": "/ɪt ɪz jˈuːsfəl tə lɜːn freɪzɪz bɪfɔːr vˈɪzɪɾɪŋ ə fˈɔːrən kˈʌntri/",
  "travelv-journey": "/ðə treɪn dʒˈɜːni tʊk əbˈaʊt fɔːr ˈaʊɚz/",
  "travelv-luggage": "/maɪ lˈʌɡɪdʒ wʌz tuː hˈɛvi tə kˈæri/",
  "travelv-passenger": "/pˈæsɪndʒɚz ʃʊd rɪmeɪn ɪn ðɛr siːts/",
  "travelv-passport": "/tʃɛk ðæt jʊr pˈæspɔːrt ɪz stɪl vˈælɪd/",
  "travelv-platform": "/ðə treɪn liːvz frʌm plˈætfɔːrm faɪv/",
  "travelv-reservation": "/aɪ hæv ə rˌɛzɚvˈeɪʃən ˈʌndɚ ðə neɪm nˈuːjɛn/",
  "travelv-route": "/ðɪs bʌs raʊt ɡoʊz θruː ðə oʊld taʊn/",
  "travelv-sightseeing": "/wiː spɛnt ðə ˌæftɚnˈuːn sˈaɪtsiːɪŋ/",
  "travelv-station": "/ðə hoʊtˈɛl ɪz ə ʃɔːrt wɔːk frʌm ðə stˈeɪʃən/",
  "travelv-suitcase": "/aɪ pækt ə laɪt dʒˈækɪt ɪn maɪ sˈuːtkeɪs/",
  "travelv-ticket": "/juː kæn baɪ ə tˈɪkɪt frʌm ðə məʃˈiːn/",
  "travelv-tour": "/wiː dʒɔɪnd ə wˈɔːkɪŋ tʊr əv ðə sˈɪɾi/",
  "travelv-traffic": "/liːv ˈɜːli bɪkˈʌz ðə trˈæfɪk ɪz hˈɛvi/",
  "travelv-transport": "/pˈʌblɪk trˈænspɔːrt ɪz tʃiːp ən rɪlˈaɪəbəl hɪr/",
  "travelv-trip": "/wiː ɑːr plˈænɪŋ ə wˈiːkɛnd trɪp tə hjuː/",
  "travelv-vehicle": "/ɪlˈɛktrɪk vˈiəkəlz ɑːr bɪkˈʌmɪŋ mɔːr kˈɑːmən/",
  "socialv-agree": "/aɪ əɡrˈiː wɪð jʊr pɔɪnt əbˈaʊt pˈʌblɪk trˈænspɔːrt/",
  "socialv-apologize": "/juː ʃʊd əpˈɑːlədʒˌaɪz fər ɚrˈaɪvɪŋ leɪt/",
  "socialv-argue": "/ðeɪ sˈʌmtaɪmz ˈɑːrɡjuː əbˈaʊt smɔːl θɪŋz/",
  "socialv-celebrate": "/wiː wɛnt aʊt tə sˈɛləbrˌeɪt hɜː nuː dʒɑːb/",
  "socialv-communicate": "/ɡʊd tiːmz kəmjˈuːnɪkˌeɪt klˈɪrli ən ˈɔfən/",
  "socialv-complain": "/ðə kˈʌstəmɚ kəmplˈeɪnd əbˈaʊt ðə sloʊ sˈɜːvɪs/",
  "socialv-contact": "/kˈɑːntækt miː ɪf juː niːd ˌɛni hɛlp/",
  "socialv-conversation": "/wiː hæd ən ˈɪntrɛstɪŋ kɑːnvɚsˈeɪʃən əbˈaʊt trˈævəl/",
  "socialv-disagree": "/ɪt ɪz oʊkˈeɪ tə dˌɪsəɡrˈiː pəlˈaɪtli/",
  "socialv-discuss": "/lɛts dɪskˈʌs ðə prˈɑːbləm ˈæftɚ lʌntʃ/",
  "socialv-encourage": "/maɪ tˈiːtʃɚ ɛŋkˈɜːrɪdʒd miː tə spiːk mɔːr/",
  "socialv-friendship": "/ðɛr frˈɛndʃɪp bɪɡˈæn ət jˌuːnɪvˈɜːsɪɾi/",
  "socialv-greet": "/ʃiː ɡriːɾɪd ˈɛvri ɡɛst wɪð ə smaɪl/",
  "socialv-introduce": "/lɛt miː ˌɪntrədˈuːs juː tə maɪ kˈɑːliːɡ/",
  "socialv-invite": "/ðeɪ ɪnvˈaɪɾɪd ʌs tə dˈɪnɚ ɔn sˈæɾɚdˌeɪ/",
  "socialv-joke": "/hiː toʊld ə fˈʌni dʒoʊk dˈʊrrɪŋ ðə breɪk/",
  "socialv-kindness": "/aɪ wɪl ˈɔːlweɪz rɪmˈɛmbɚ hɜː kˈaɪndnəs/",
  "socialv-message": "/liːv miː ə mˈɛsɪdʒ wɛn juː ɚrˈaɪv/",
  "socialv-polite": "/ɪt ɪz pəlˈaɪt tə seɪ θæŋk juː/",
  "socialv-promise": "/aɪ prˈɑːmɪs tə kɔːl juː ˈæftɚ wɜːk/",
  "socialv-refuse": "/hiː pəlˈaɪtli rɪfjuːzd ðə ɪnvɪtˈeɪʃən/",
  "socialv-respond": "/pliːz rɪspɑːnd tə ðə ˈiːmeɪl baɪ təmˈɑːroʊ/",
  "socialv-trust": "/ɪt teɪks taɪm tə bɪld trʌst/",
  "socialv-welcome": "/ðeɪ wˈɛlkʌmd ʌs ˌɪntʊ ðɛr hoʊm/",
  "healthv-ache": "/maɪ lɛɡz eɪk ˈæftɚ ðə lɔŋ wɔːk/",
  "healthv-active": "/stˈeɪɪŋ ˈæktɪv ɪz ɡʊd fər jʊr hɑːrt/",
  "healthv-advice": "/ðə dˈɑːktɚ ɡeɪv miː sʌm jˈuːsfəl ədvˈaɪs/",
  "healthv-balance": "/ə hˈɛlθi laɪf niːdz ə bˈæləns bɪtwiːn wɜːk ən rɛst/",
  "healthv-breathe": "/briːð slˈoʊli wɛn juː fiːl nˈɜːvəs/",
  "healthv-check-up": "/aɪ hæv ə dˈɛntəl tʃˈɛkˈʌp twaɪs ə jɪr/",
  "healthv-cough": "/hiː steɪd hoʊm bɪkˈʌz əv ə bæd kɔf/",
  "healthv-diet": "/ə bˈælənst dˈaɪət ɪŋklˈuːdz plˈɛnti əv vˈɛdʒɪɾəbəlz/",
  "healthv-exercise": "/rˈɛɡjʊlɚ ˈɛksɚsˌaɪz ɪmprˈuːvz jʊr muːd/",
  "healthv-fit": "/sˈaɪklɪŋ hɛlps miː kiːp fɪt/",
  "healthv-headache": "/tuː mʌtʃ skriːn taɪm ɡɪvz miː ə hˈɛdeɪk/",
  "healthv-healthy": "/wiː traɪ tə kʊk hˈɛlθi miːlz ət hoʊm/",
  "healthv-illness": "/ðə ˈɪlnəs kɛpt hɜː əwˈeɪ frʌm wɜːk fər ə wiːk/",
  "healthv-medicine": "/teɪk ðɪs mˈɛdəsən ˈæftɚ miːlz/",
  "healthv-pain": "/aɪ fɛlt ə ʃɑːrp peɪn ɪn maɪ ʃˈoʊldɚ/",
  "healthv-recover": "/ɪt tʊk hɪm ə mʌnθ tə rɪkˈʌvɚ fˈʊli/",
  "healthv-relax": "/mjˈuːzɪk hɛlps miː rɪlæks ˈæftɚ ə bˈɪzi deɪ/",
  "healthv-rest": "/juː niːd tə rɛst ɪf juː fiːl tˈaɪɚd/",
  "healthv-sleep": "/moʊst ədˈʌlts niːd sˈɛvən ər eɪt ˈaʊɚz əv sliːp/",
  "healthv-stress": "/plˈænɪŋ əhˈɛd kæn rɪduːs strɛs/",
  "healthv-symptom": "/ə haɪ tˈɛmprɪtʃɚ kæn biː ə sˈɪmptəm əv ɪnfˈɛkʃən/",
  "healthv-treatment": "/ðə trˈiːtmənt hɛlpt hɜː fiːl bˈɛɾɚ/",
  "healthv-tired": "/aɪ fiːl tˈaɪɚd wɛn aɪ duː nɑːt sliːp ɪnˈʌf/",
  "healthv-well": "/ʃiː wʌz ɪl jˈɛstɚdˌeɪ bʌt fiːlz wɛl tədˈeɪ/",
} as const;

